### ISSUE TITLE
Onediff load error

### ISSUE THREAD

**Issue by kakachiex2** [siliconflow/onediff_comfy_nodes#1]
I get this error wen instaled onediff

FileNotFoundError: [Errno 2] No such file or directory: 'K:\\ComfyUI\\ComfyUI\\custom_nodes\\onediff\\__init__.py'

Cannot import K:\ComfyUI\ComfyUI\custom_nodes\onediff module for custom nodes: [Errno 2] No such file or directory: 'K:\\ComfyUI\\ComfyUI\\custom_nodes\\onediff\\__init__.py'
Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI\ComfyUI\custom_nodes\onediff_comfy_nodes\__init__.py", line 2, in <module>
    from ._config import _USE_UNET_INT8
  File "K:\ComfyUI\ComfyUI\custom_nodes\onediff_comfy_nodes\_config.py", line 15, in <module>
    import register_comfy  # load plugins
    ^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\custom_nodes\onediff_comfy_nodes\infer_compiler_registry\register_comfy\__init__.py", line 1, in <module>
    from onediff.infer_compiler import register
ModuleNotFoundError: No module named 'onediff.infer_compiler'

Cannot import K:\ComfyUI\ComfyUI\custom_nodes\onediff_comfy_nodes module for custom nodes: No module named 'onediff.infer_compiler'

**Comment by kakachiex2** [comment]
I follow the process and this is what I have in the nodes folder it is correct:
![Screenshot 2024-01-06 235601](https://github.com/siliconflow/onediff_comfy_nodes/assets/1762112/f78483a2-0d33-44d5-a9d4-22565c75dc8d)

**Comment by kakachiex2** [comment]
Were do I install the first onediff process

**Comment by fs920105** [comment]
Same problem.
Traceback (most recent call last):
  File "D:\sd-webui-aki\ComfyUI\ComfyUI/windows\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd-webui-aki\ComfyUI\ComfyUI_windows\ComfyUI\custom_nodes\onediff_comfy_nodes\__init__.py", line 2, in <module
    From . _config to import the _USE_UNET_INT8
  File "D:\sd-webui-aki\ComfyUI\ComfyUI_windows\ComfyUI\custom_nodes\onediff_comfy_nodes\_config.py", line 15, in <module>
    import register_comfy # load plugin
    ^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd-webui-aki\ComfyUI\ComfyUI_windows\ComfyUI\custom_nodes\onediff_comfy_nodes\infer_compiler_registry\register_comfy\__init __.py", line 1, in <module>
    Import register from onediff.infer_compiler
Module not found error: There is no module named 'onediff.infer_compiler'.

Unable to import D:sd-webui-aki\ComfyUI\ComfyUI\windows\ComfyUI\custom_nodes\onediff_comfy_nodes module for custom nodes: no module named 'onediff.infer_compiler' available

**Comment by fs920105** [comment]
I tossed a moment to find that this error may be caused by not installing the CUDA Acceleration Toolkit and Visual Studio these, I looked at these two program files are a little large (about 30G or so seems to be), I do not have enough space to give up down the fold, I guess that is the reason, enough space to this step can be installed to see the results of these two things.

**Comment by sd2530615** [comment]
same error ,did you fixe it yet?

**Comment by leegang** [comment]
同样的错误。

**Comment by leegang** [comment]
知道原因了， 你可能是用 comfyUI CLI  安装的。
```
git clone https://github.com/siliconflow/onediff.git
cd onediff && pip install -e .
ln -s $(pwd)/onediff_comfy_nodes path/to/ComfyUI/custom_nodes/
# or
# cp -r onediff_comfy_nodes path/to/ComfyUI/custom_nodes/
```
用第二种方法就可以了。
