### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Uniky** [siliconflow/onediff_comfy_nodes#3]
I've already installed the required packages into ComfyUI_windows_portable/python_embeded/Lib/site-packages folder:
![image](https://github.com/siliconflow/onediff_comfy_nodes/assets/24896456/23b80d29-f651-44de-adc5-6dbf06c35522)
But when lauching comfyUI, I got this error:
Traceback (most recent call last):
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes\__init__.py", line 3, in <module>
    from ._nodes import (ModelSpeedup, OneDiffApplyModelBooster,
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes\_nodes.py", line 6, in <module>
    from .utils.import_utils import is_nexfort_available  # type: ignore
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes\utils\__init__.py", line 1, in <module>
    from .import_utils import is_nexfort_available, is_oneflow_available
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes\utils\import_utils.py", line 7, in <module>
    import oneflow
  File "E:\StableDiffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\oneflow\__init__.py", line 21, in <module>
    raise RuntimeError("This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow")
RuntimeError: This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow

Cannot import E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes module for custom nodes: This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow

**Comment by kenic123** [comment]
不支持windows运行，别试了，库没有。只有linux版的

**Comment by quqiufeng** [comment]
> 不支持 windows 运行，别试了，库没有。只有 linux 版的

这不是搞笑么
